spring:
  profiles:
    active: test
---
spring:
  datasource:
    url: jdbc:mysql://test.com:3306/test
    username: root
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
    schema: classpath:schema.sql
    initialization-mode: embedded
  profiles: test
