spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:test_db
    initialization-mode: embedded
    driver-class-name: org.h2.Driver
    schema: classpath:schema.sql
    data: classpath:data.sql
    continue-on-error: false
    platform: h2
  jpa:
    show-sql: true